apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config

data:
  config.json: |
    {
      "storage": {
        "postgresql": {
          "connection_url": "{{ .Values.vault.storage.databaseUrl }}"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      }
    }
