apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.json: |
    {
      "storage": {
        "postgresql": {
          "connection_url": "postgresql://vault:vaultpassword@postgres-service:5432/vault"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      },
      "ui": true,
      "disable_mlock": true
    }
